#include "ISXPyPCH.h"
#include "ISXPy.h"

BOOST_PYTHON_MODULE(pyisxeq2)
{
	using namespace boost::python;

	class_<LSOBJECT>("LSObject", no_init);

	class_<py_lsobject>("PyLSObject", init<LSOBJECT&>())
		.add_property("to_bool", &py_lsobject::get_bool_from_lso)
		.add_property("to_byte", &py_lsobject::get_byte_from_lso)
		.add_property("to_float", &py_lsobject::get_float_from_lso)
		.add_property("to_int", &py_lsobject::get_int_from_lso)
		.add_property("to_int64", &py_lsobject::get_int64_from_lso)
		.add_property("to_string", &py_lsobject::get_string_from_lso)
		.add_property("to_uint", &py_lsobject::get_uint_from_lso)
		.def("to_lso", &py_lsobject::get_lso, return_value_policy<reference_existing_object>())
	;

	class_<py_actor, bases<py_lsobject>>("actor")
		.add_property("aura", &py_actor::get_aura)
		.add_property("char_class", &py_actor::get_class)
		.def("check_collision", &py_actor::check_collision, py_actor::check_collision_overloads(args("to_x", "to_y", "to_z")))
		.add_property("collision_radius", &py_actor::get_collision_radius)
		.add_property("collision_scale", &py_actor::get_collision_scale)
		.def("con_color", &py_actor::get_con_color, py_actor::get_con_color_overloads(args("as_rgb")))
		.add_property("current_animation", &py_actor::get_current_animation)
		.add_property("distance", &py_actor::get_distance)
		.add_property("distance2d", &py_actor::get_distance2d)
		.add_property("effective_level", &py_actor::get_effective_level)
		.add_property("faction", &py_actor::get_faction)
		.add_property("faction_standing", &py_actor::get_faction_standing)
		.add_property("flying_using_mount", &py_actor::get_flying_using_mount)
		.add_property("gender", &py_actor::get_gender)
		.add_property("guild", &py_actor::get_guild)
		.add_property("heading", &py_actor::get_heading)
		.add_property("heading_to", &py_actor::get_heading_to)
		.add_property("heading_to_as_compass_bearing", &py_actor::get_heading_to_as_compass_bearing)
		.add_property("id", &py_actor::get_id)
		.add_property("in_my_group", &py_actor::get_in_my_group)
		.add_property("interactable", &py_actor::get_interactable)
		.add_property("is_afk", &py_actor::get_is_afk)
		.add_property("is_aggro", &py_actor::get_is_aggro)
		.add_property("is_a_pet", &py_actor::get_is_a_pet)
		.add_property("is_camping", &py_actor::get_is_camping)
		.add_property("is_encounter_broken", &py_actor::get_is_encounter_broken)
		.add_property("is_epic", &py_actor::get_is_epic)
		.add_property("is_heroic", &py_actor::get_is_heroic)
		.add_property("is_lfg", &py_actor::get_is_lfg)
		.add_property("is_lfw", &py_actor::get_is_lfw)
		.add_property("is_linkdead", &py_actor::get_is_linkdead)
		.add_property("is_locked", &py_actor::get_is_locked)
		.add_property("is_my_pet", &py_actor::get_is_my_pet)
		.add_property("is_banker", &py_actor::get_is_banker)
		.add_property("is_chest", &py_actor::get_is_chest)
		.add_property("is_invis", &py_actor::get_is_invis)
		.add_property("is_merchant", &py_actor::get_is_merchant)
		.add_property("is_named", &py_actor::get_is_named)
		.add_property("is_solo", &py_actor::get_is_solo)
		.add_property("is_stealthed", &py_actor::get_is_invis)
		.add_property("is_swimming", &py_actor::get_is_swimming)
		.add_property("health", &py_actor::get_health)
		.add_property("last_name", &py_actor::get_last_name)
		.add_property("level", &py_actor::get_level)
		.add_property("loc", &py_actor::get_loc)
		.add_property("mood", &py_actor::get_mood)
		.add_property("name", &py_actor::get_name)
		.add_property("get_num_effects", &py_actor::get_num_effects)
		.add_property("on_flying_mount", &py_actor::get_on_flying_mount)
		.add_property("pet", &py_actor::get_pet)
		.add_property("power", &py_actor::get_power)
		.add_property("race", &py_actor::get_race)
		.add_property("speed", &py_actor::get_speed)
		.add_property("suffix_title", &py_actor::get_suffix_title)
		.add_property("swimming_speed_mod", &py_actor::get_swimming_speed_mod)
		.add_property("target", &py_actor::get_target)
		.add_property("target_ring_radius", &py_actor::get_target_ring_radius)
		.add_property("threat_to_me", &py_actor::get_threat_to_me)
		.add_property("threat_to_next", &py_actor::get_threat_to_next)
		.add_property("threat_to_pet", &py_actor::get_threat_to_pet)
		.add_property("tint_flags", &py_actor::get_tint_flags)
		.add_property("type", &py_actor::get_type)
		.add_property("velocity", &py_actor::get_velocity)
		.add_property("visual_variant", &py_actor::get_visual_variant)
		.add_property("who_following", &py_actor::get_who_following)
		.add_property("who_following_id", &py_actor::get_who_following_id)
		.add_property("x", &py_actor::get_x)
		.add_property("y", &py_actor::get_y)
		.add_property("z", &py_actor::get_z)
		.def("get_effects", &py_actor::get_effects)
	;

	class_<py_eq2, bases<py_lsobject>>("eq2")
		.add_property("server_name", &py_eq2::get_server_name)
		.def("query_actors", &py_eq2::query_actors, py_eq2::query_actors_overloads(args("actor_list", "query")));

	class_<py_isxeq2, bases<py_lsobject>>("isxeq2")
		.def("add_loc", &py_isxeq2::add_loc, py_isxeq2::add_loc_overloads(args("label", "notes")))
		.add_property("affliction_events_on", &py_isxeq2::get_affliction_events_on)
		.add_property("api_version", &py_isxeq2::get_api_version)
		.def("clear_abilities_cache", &py_isxeq2::clear_abilities_cache)
		.def("disable_affliction_events", &py_isxeq2::disable_affliction_events)
		.def("disable_custom_zoning_text", &py_isxeq2::disable_custom_zoning_text)
		.def("enable_affliction_events", &py_isxeq2::enable_affliction_events)
		.def("enable_custom_zoning_text", &py_isxeq2::enable_custom_zoning_text)
		.def("eq2locs_count", &py_isxeq2::get_eq2locs_count, py_isxeq2::get_eq2locs_count_overloads(args("all_zones")))
		.add_property("is_ready", &py_isxeq2::get_is_ready)
		.def("is_valid_eq2press_key", &py_isxeq2::get_is_valid_eq2press_key, args("key"))
		.def("popup", &py_isxeq2::popup, py_isxeq2::popup_overloads(args("message", "title", "status")))
		.def("reset_internal_vending_system", &py_isxeq2::reset_internal_vending_system)
		.def("set_actor_events_range", &py_isxeq2::set_actor_events_range, args("range"))
		.def("set_actor_events_time_interval", &py_isxeq2::set_actor_events_time_interval, args("time"))
		.def("set_affliction_events_time_interval", &py_isxeq2::set_affliction_events_time_interval, args("time"))
		.add_property("version", &py_isxeq2::get_version);

	class_<py_effect_info, bases<py_lsobject>>("effect_info")
		.add_property("description", &py_effect_info::get_description)
		.add_property("name", &py_effect_info::get_name)
		.add_property("type", &py_effect_info::get_type);

	class_<py_effect, bases<py_lsobject>>("effect")
		.add_property("back_drop_icon_id", &py_effect::get_back_drop_icon_id)
		.add_property("current_increments", &py_effect::get_current_increments)
		.add_property("duration", &py_effect::get_duration)
		.add_property("effect_info", &py_effect::get_effect_info)
		.add_property("id", &py_effect::get_id)
		.add_property("is_effect_info_available", &py_effect::get_is_effect_info_available)
		.add_property("main_icon_id", &py_effect::get_main_icon_id)
		.add_property("max_duration", &py_effect::get_max_duration);

	class_<py_maintained, bases<py_lsobject>>("maintained")
		.add_property("concentration_cost", &py_maintained::get_concentration_cost)
		.add_property("current_increments", &py_maintained::get_current_increments)
		.add_property("damage_remaining", &py_maintained::get_damage_remaining)
		.add_property("duration", &py_maintained::get_duration)
		.add_property("is_beneficial", &py_maintained::get_is_beneficial)
		.add_property("max_duration", &py_maintained::get_max_duration)
		.add_property("name", &py_maintained::get_name)
		.add_property("target", &py_maintained::get_target)
		.add_property("target_type", &py_maintained::get_target_type)
		.add_property("uses_remaining", &py_maintained::get_uses_remaining);

	class_<py_actor_effect, bases<py_lsobject>>("actor_effect")
		.add_property("back_drop_icon_id", &py_actor_effect::get_back_drop_icon_id)
		.add_property("current_increments", &py_actor_effect::get_current_increments)
		.add_property("is_effect_info_available", &py_actor_effect::get_is_effect_info_available)
		.add_property("main_icon_id", &py_actor_effect::get_main_icon_id)
		.add_property("effect_info", &py_actor_effect::get_effect_info)
		.add_property("id", &py_actor_effect::get_id);

	class_<py_character, bases<py_lsobject>>("character")
		.add_property("archetype", &py_character::get_archetype)
		.add_property("at_char_select", &py_character::get_at_char_select)
		.add_property("base_strength", &py_character::get_base_strength)
		.add_property("breath", &py_character::get_breath)
		.add_property("char_class", &py_character::get_class)
		.add_property("copper", &py_character::get_copper)
		.add_property("current_health", &py_character::get_current_health)
		.add_property("current_power", &py_character::get_current_power)
		.add_property("effective_level", &py_character::get_effective_level)
		.add_property("exp_bubble", &py_character::get_exp_bubble)
		.add_property("exp_current", &py_character::get_exp_current)
		.add_property("exp_debt_current", &py_character::get_exp_debt_current)
		.add_property("exp_next_level", &py_character::get_exp_next_level)
		.add_property("exp_percent", &py_character::get_exp_percent)
		.add_property("gender", &py_character::get_gender)
		.add_property("gold", &py_character::get_gold)
		.add_property("heading", &py_character::get_heading)
		.add_property("health_regen", &py_character::get_health_regen)
		.add_property("in_game_world", &py_character::get_in_game_world)
		.add_property("is_moving", &py_character::get_is_moving)
		.add_property("level", &py_character::get_level)
		.add_property("max_conc", &py_character::get_max_conc)
		.add_property("max_health", &py_character::get_max_health)
		.add_property("max_power", &py_character::get_max_power)
		.add_property("name", &py_character::get_name)
		.add_property("platinum", &py_character::get_platinum)
		.add_property("power_regen", &py_character::get_power_regen)
		.add_property("race", &py_character::get_race)
		.add_property("silver", &py_character::get_silver)
		.add_property("strength", &py_character::get_strength)
		.add_property("subclass", &py_character::get_subclass)
		.add_property("ts_archetype", &py_character::get_ts_archetype)
		.add_property("ts_class", &py_character::get_ts_class)
		.add_property("ts_level", &py_character::get_ts_level)
		.add_property("ts_subclass", &py_character::get_ts_subclass)
		.add_property("ts_vitality", &py_character::get_ts_vitality)
		.add_property("ts_vitality_lower_marker", &py_character::get_ts_vitality_lower_marker)
		.add_property("ts_vitality_overflow_marker", &py_character::get_ts_vitality_overflow_marker)
		.add_property("ts_vitality_upper_marker", &py_character::get_ts_vitality_upper_marker)
		.add_property("used_conc", &py_character::get_used_conc)
		.add_property("water_depth", &py_character::get_water_depth)
		.add_property("vitality", &py_character::get_vitality)
		.add_property("vitality_lower_marker", &py_character::get_vitality_lower_marker)
		.add_property("vitality_overflow_marker", &py_character::get_vitality_overflow_marker)
		.add_property("vitality_upper_marker", &py_character::get_vitality_upper_marker)
		.add_property("x", &py_character::get_x)
		.add_property("y", &py_character::get_y)
		.add_property("z", &py_character::get_z)
		.def("check_collision", &py_character::check_collision)
		.def("query_effects", &py_character::query_effects, py_character::query_effects_overloads(args("effect_list", "query")))
		.def("get_maintained", &py_character::get_maintained)
		.def("heading_to", &py_character::heading_to)
		.def("heading_to_as_compass_bearing", &py_character::heading_to_as_compass_bearing);

	class_<py_point3f, bases<py_lsobject>>("point3f")
		.add_property("x", &py_point3f::get_x)
		.add_property("y", &py_point3f::get_y)
		.add_property("z", &py_point3f::get_z)
		.def("xyz", &py_point3f::get_xyz, py_point3f::get_xyz_overloads(args("separator")));
}

void Initialize_Module_PyISXEQ2()
{
	PyImport_AppendInittab("pyisxeq2", PyInit_pyisxeq2);
}

void Shutdown_Module_PyISXEQ2()
{

}